Name: Annanya Jain

Through this assessment, I aim to process security data from an input file by following the below steps:

1. Read and process the security reference input file (corp_pfd.dif)
2. Limiting columns to retain only those found in reference field list (reference_fields.csv)
3. Comparing securities in the the input file with the reference securities dataset (reference_securities.csv) and identify new securities not present in the latter.
4. Reshape and restructure the data for security data output.

In [18]:
import pandas as pd
import csv
import re
from datetime import datetime
import warnings

In [19]:
# File Paths for input and output files. 
# Ensure input files are in the same directory as the code file. 

input_dif_file = 'corp_pfd.dif'
reference_fields_file = 'reference_fileds.csv'
reference_securities_file = 'reference_securities.csv'

output_csv_file = 'output_corp_pfd.csv'

# Required Output files:
new_securities_output_file = 'new_securities.csv'
security_data_output_file = 'security_data.csv'

In [20]:
def read_csv(file_path):
  ''' Reads a CSV file into a Pandas Dataframe'''
  return pd.read_csv(file_path)

STEP 1: Read Security Reference input file and convert it to DataFrame using column names supplied in input file: corp_pfd.dif

In [21]:
def input_dif_to_csvfile(dif_file, csv_file):
  with open(dif_file, 'r') as infile, open(csv_file, 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)

    column_fields = []
    data_rows = []

    # Initialised the pointer for writer object to be False for fields_section & data_section
    fields_section = False
    data_section = False

    for line in infile:
      line = line.strip() # stripping to remove any leading or trailing spaces in the string

      # checking if the line to write is inside the fields section
      if line == "START-OF-FIELDS":
        fields_section = True
        continue

      if line == "END-OF-FIELDS":
        fields_section = False
        continue

      # checking if the line to write is inside the data section
      if line == "START-OF-DATA":
        data_section = True
        continue

      if line == "END-OF-DATA":
        # Exiting the loop as all the data needed has been written to the csv file
        break

      # skipping the line which is either empty or if the line starts with '#' as it is not a column name and just a description of the column names under it.
      if not line or line.startswith("#"):
        continue

      if fields_section:
        column_fields.append(line)
        # after appending the line to the column_fields array, move to the next iteration of loop ( i.e check next line).
        continue

      if data_section:
        # splitting each data row into each column value through pipe '|' delimiter
        data_row = re.split(r'\s*\|\s*', line)

        while data_row and data_row[-1] == '':
          data_row.pop()
        data_rows.append(data_row)

        # after appending the line to the data_rows array, move to the next iteration of loop ( i.e check next line in data section).
        continue

    # Writing into csvfile once the column_fields and data_rows arrays are appended with the extracted data.
    if column_fields:
      writer.writerow(column_fields)
    writer.writerows(data_rows)

  print(f"Conversion from dif file to csv file is completed and is saved to {csv_file}\n")

input_dif_to_csvfile(input_dif_file, output_csv_file)
df = read_csv(output_csv_file)
df

Conversion from dif file to csv file is completed and is saved to output_corp_pfd.csv

,TICKER_YELLOW_KEY,ST1,REF1,TICKER,CPN,MATURITY,SERIES,NAME,SHORT_NAME,ISSUER_INDUSTRY,...,INDUSTRY_GROUP_NUM,INDUSTRY_SECTOR_NUM,ISSUERS_STOCK,INFLATION_LAG,MAKE_WHOLE_CALL_SPREAD,ISSUER_BULK,ID_BB_SEC_NUM_DES,FEED_SOURCE,ID_BB_GLOBAL_COMPANY,ID_BB_GLOBAL_COMPANY_NAME
0,AS3629704 Corp,-1,210,MTRC,2.560000,20210502.0,EMTN,MTR CORP CI LTD,MTR CORP CI LTD,SPECIAL PURPOSE,...,20091,10011,NaN,N.A.,N.A.,MTR CORP CI LTD,MTRC 2.56 05/02/21 EMTN,BGN,BBG001GBHFS3,MTR Corp CI Ltd
1,AS3764410 Corp,-1,210,CILBAR,33.921460,20210502.0,I,CILBRAKE SRL,CILBRAKE SRL,INDUSTRIAL,...,20022,10004,NaN,N.A.,N.A.,CILBRAKE SRL,CILBAR F 05/02/21 I,BGN,BBG00KRC8B42,Cilbrake SRL
2,ZS2774298 Corp,-1,210,REDPRO,9.875000,20210502.0,NaN,REDCO PROPERTIES GROUP,REDCO PROPERTIES,FINANCIAL,...,20058,10008,NaN,N.A.,N.A.,REDCO PROPERTIES GROUP,REDPRO 9.875 05/02/21,BGN,BBG005WQH7K9,Redco Properties Group Ltd
3,4590568X8 Corp,0,210,IBRD,N.A.,20831201.0,NaN,INTL BK RECON & DEVELOP,INT BK RECON&DEV,SUPRA-NATIONAL,...,20073,10010,NaN,N.A.,N.A.,INTL BK RECON & DEVELOP,IBRD V0 12/01/83,BGN,BBG001FHC3T2,International Bank for Reconstruction & Develo...
4,AF1220108 Corp,0,210,POSADA,7.875000,20220630.0,144A,GRUPO POSADAS SAB CV,GRUPO POSADAS,INDUSTRIAL,...,20029,10004,NaN,N.A.,50.000,GRUPO POSADAS SAB CV,POSADA 7.875 06/30/22 144A,BGN,BBG001FGB048,Grupo Posadas SAB de CV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2891,ZS8358328 Corp,0,210,USJACU,9.875000,20231109.0,144A,USJ ACUCAR E ALCOOL SA,USJ ACUCAR E AL,INDUSTRIAL,...,20040,10005,NaN,N.A.,N.A.,USJ ACUCAR E ALCOOL SA,USJACU 9.875 11/09/23 144A,BGN,BBG002R2PND9,USJ-Acucar e Alcool S/A
2892,ZS8402340 Corp,0,210,USJACU,9.875000,20231109.0,REGS,USJ ACUCAR E ALCOOL SA,USJ ACUCAR E AL,INDUSTRIAL,...,20040,10005,NaN,N.A.,N.A.,USJ ACUCAR E ALCOOL SA,USJACU 9.875 11/09/23 REGS,BGN,BBG002R2PND9,USJ-Acucar e Alcool S/A
2893,ZS8705577 Corp,0,210,LTMCI,3.600000,20290415.0,E,LATAM AIRLINES GROUP SA,LATAM AIR,INDUSTRIAL,...,20018,10004,NaN,1,N.A.,LATAM AIRLINES GROUP SA,LTMCI 3.6 04/15/29 E,BGN,BBG001FGQ4Q0,Latam Airlines Group SA
2894,ZS8952088 Corp,0,210,SECUCL,4.400000,20240415.0,H,FACTORING SECURITY SA,FACTORING SECURI,FINANCIAL,...,20054,10008,NaN,N.A.,N.A.,FACTORING SECURITY SA,SECUCL 4.4 04/15/24 H,BGN,BBG001H1W8B1,Factoring Security SA
2895,ZS9312746 Corp,0,210,GMFIN,4.830000,20210528.0,19,GM FINANCIAL DE MEXICO,GM FIN DE MEXICO,FINANCIAL,...,20054,10008,NaN,N.A.,N.A.,GM FINANCIAL DE MEXICO,GMFIN F 05/28/21 19,BGN,BBG001GG14X8,GM Financial de Mexico SA de CV SOFOM ER

STEP 2: Limit columns in DataFrame to only those found in reference_fields.csv

In [22]:
def limiting_df_columns_to_reference_fields(df, reference_fields_file):
  reference_fields_df = read_csv(reference_fields_file)
  reference_fields = reference_fields_df['field'].tolist()

  # Retrieving only the column names that exist in both the input file and reference_fields file.
  common_columns = list(set(df.columns) & set(reference_fields))
  return df[common_columns]

df = limiting_df_columns_to_reference_fields(df, reference_fields_file)
df

,MATURITY,ID_BB_GLOBAL,CNTRY_OF_INCORPORATION,CONTINGENT_CONVERSION,ID_CUSIP,CV_COMMON_TICKER_EXCH,FIRST_SETTLE_DT,INDUSTRY_SUBGROUP,ISSUER_BULK,CV_COMMON_TICKER,...,CNTRY_OF_DOMICILE,CV_CNVS_RATIO,DEFAULTED,ID_CUSIP_REAL,ID_ISIN,CUR_CPN,INFLATION_LINKED_INDICATOR,INDUSTRY_GROUP,CPN,AMT_OUTSTANDING
0,20210502.0,BBG00KRL8RW6,KY,NaN,AS3629704,NaN,20180502,Transport-Services,MTR CORP CI LTD,NaN,...,HK,NaN,N,NaN,HK0000416609,NaN,N,Transportation,2.560000,4.130000e+08
1,20210502.0,BBG00KRMSZ63,AR,NaN,AS3764410,NaN,20180502,Distribution/Wholesale,CILBRAKE SRL,NaN,...,AR,NaN,N,NaN,ARCILB560016,.000000,N,Distribution/Wholesale,33.921460,6.666680e+06
2,20210502.0,BBG00NZ74Q67,KY,NaN,ZS2774298,NaN,20190502,Real Estate Oper/Develop,REDCO PROPERTIES GROUP,NaN,...,CN,NaN,N,NaN,XS1989092116,NaN,N,Real Estate,9.875000,1.285240e+08
3,20831201.0,BBG00000F4P6,SNAT,NaN,4590568X8,NaN,19841217,Supranational Bank,INTL BK RECON & DEVELOP,NaN,...,US,NaN,N,4590568X8,CA4590568X88,N.A.,N,Multi-National,N.A.,2.000000e+08
4,20220630.0,BBG009HTFZR5,MX,NaN,400489AH3,NaN,20150630,Hotels&Motels,GRUPO POSADAS SAB CV,NaN,...,MX,NaN,Y,400489AH3,US400489AH37,NaN,N,Lodging,7.875000,3.926050e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2891,20231109.0,BBG00P8SNLL9,BR,NaN,90346JAC6,NaN,20190524,Sugar,USJ ACUCAR E ALCOOL SA,NaN,...,BR,NaN,Y,90346JAC6,US90346JAC62,NaN,N,Food,9.875000,2.859103e+08
2892,20231109.0,BBG00P8SXNZ9,BR,NaN,ZS8402340,NaN,20190524,Sugar,USJ ACUCAR E ALCOOL SA,NaN,...,BR,NaN,Y,NaN,USP9634CAC57,NaN,N,Food,9.875000,3.011077e+08
2893,20290415.0,BBG00P96HDD0,CL,NaN,ZS8705577,NaN,20190415,Airlines,LATAM AIRLINES GROUP SA,NaN,...,CL,NaN,Y,NaN,NaN,NaN,Y,Airlines,3.600000,5.000000e+06
2894,20240415.0,BBG00P9C1MJ8,CL,NaN,ZS8952088,NaN,20190415,Finance-Other Services,FACTORING SECURITY SA,NaN,...,CL,NaN,N,NaN,NaN,NaN,N,Diversified Finan Serv,4.400000,4.000000e+10
2895,20210528.0,BBG00PBCD484,MX,NaN,ZS9312746,NaN,20190531,Finance-Auto Loans,GM FINANCIAL DE MEXICO,NaN,...,MX,NaN,N,NaN,MX91GM130022,4.830000,N,Diversified Finan Serv,4.830000,1.000000e+09

STEP 3: Comparing the security data in input file against reference_securities.csv file using ID_BB_GLOBAL as the unique identifier. The output file only includes securities from the input file that is not in the reference file.

In [23]:
def compare_with_reference_securities(df, reference_securities_file):
  reference_securities_df = read_csv(reference_securities_file)
  df_security = df.copy()

  # Normalizing column names for both dataframes by stripping spaces and converting to lowercase.
  reference_securities_df.columns = reference_securities_df.columns.str.strip().str.lower()
  df_security.columns = df_security.columns.str.lower()

  # Ensuring the input dataframe has same structure as the reference_securities_file i.e have same column names.
  df_security = df_security[reference_securities_df.columns]

  # Removing any duplicates based on the column 'id_bb_global' and keeping only first occurence.
  df_security = df_security.drop_duplicates(subset=['id_bb_global'], keep='first')

  # Performing a left join between input securities and reference securities on 'id_bb_global'
  df_security_merged = pd.merge(df_security, reference_securities_df, on='id_bb_global', how='left', indicator= True)

  # Filtering only those securities not found in reference file (i.e the 'left_only' column in the '_merge' column)
  new_security = df_security_merged[df_security_merged['_merge'] == 'left_only']
  new_security = new_security.drop(columns=['_merge'], axis=1)

  # Removing columns that end with '_y' and renaming columns ending with '_x' back to their original names
  new_security = new_security.loc[:, ~new_security.columns.str.endswith('_y')]
  new_security = new_security.rename(lambda x: x[:-2] if x.endswith('_x') else x, axis=1)
  return new_security

new_security = compare_with_reference_securities(df, reference_securities_file)
new_security.to_csv(new_securities_output_file, index=False)
print(f"The new security csv file has been saved to {new_securities_output_file}\n")
new_security

The new security csv file has been saved to new_securities.csv

,id_bb_global,id_isin,id_cusip,id_sedol1,ticker,name,exch_code,issuer,market_sector_des
1446,BBG000064N91,SE0001233990,ED5429110,B7NCQ92,OREKON,ORESUNDSKONSORTIET,NOMX STOCKHOLM,ORESUNDSKONSORTIET,Govt

STEP 4: Creating security_data.csv file by melting/reshaping the input dataframe containing the security data.

In [24]:
warnings.filterwarnings('ignore', category=DeprecationWarning)

def create_security_data(df):
  df_security_data = df.drop_duplicates(subset='ID_BB_GLOBAL', keep='first')

  # Reshaped data using pandas' melt() function that converts wide format into long format (each row as field-value pair).
  melted_df = pd.melt(df_security_data, id_vars=['ID_BB_GLOBAL'], var_name='FIELD', value_name='VALUE')
  melted_df['SOURCE'] = 'corp_pfd.dif'
  melted_df['TSTAMP'] = datetime.now().strftime("%Y-%m-%d")

  # Grouped by 'ID_BB_GLOBAL' ensuring all related rows together (i.e those having same ids) without changing the original order.
  melted_df = melted_df.groupby('ID_BB_GLOBAL', sort= False).apply(lambda x: x).reset_index(drop=True)
  return melted_df

security_data = create_security_data(df)
security_data.to_csv(security_data_output_file, index=False)

print(f"\n The securities data csv file has been saved to {security_data_output_file}\n")
security_data

 The securities data csv file has been saved to security_data.csv

,ID_BB_GLOBAL,FIELD,VALUE,SOURCE,TSTAMP
0,BBG00KRL8RW6,MATURITY,20210502.0,corp_pfd.dif,2025-03-16
1,BBG00KRL8RW6,CNTRY_OF_INCORPORATION,KY,corp_pfd.dif,2025-03-16
2,BBG00KRL8RW6,CONTINGENT_CONVERSION,NaN,corp_pfd.dif,2025-03-16
3,BBG00KRL8RW6,ID_CUSIP,AS3629704,corp_pfd.dif,2025-03-16
4,BBG00KRL8RW6,CV_COMMON_TICKER_EXCH,NaN,corp_pfd.dif,2025-03-16
...,...,...,...,...,...
141899,BBG00PBCD484,CUR_CPN,4.830000,corp_pfd.dif,2025-03-16
141900,BBG00PBCD484,INFLATION_LINKED_INDICATOR,N,corp_pfd.dif,2025-03-16
141901,BBG00PBCD484,INDUSTRY_GROUP,Diversified Finan Serv,corp_pfd.dif,2025-03-16
141902,BBG00PBCD484,CPN,4.830000,corp_pfd.dif,2025-03-16
141903,BBG00PBCD484,AMT_OUTSTANDING,1000000000.0,corp_pfd.dif,2025-03-16